version: '2'
services:
  ci-mysql:
    ports:
      - "6612:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    image: mysql:5.7.16
    container_name: demo-mysql
    