version: '2'
services:
  mysql:
    container_name: bookstack_mysql
    image: mysql:5.7.31
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - ./data/mysql:/var/lib/mysql

  bookstack:
    container_name: bookstack
    image: solidnerd/bookstack:0.29.3
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - ./data/uploads:/var/www/bookstack/public/uploads
    - ./data/storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"

volumes:
 mysql:
 uploads:
 storage-uploads: