version: '2'
services:
  qiandao:
    image: fangzhengjin/qiandao:latest
    container_name: qiandao
    restart: always
    ports:
      - "8000:80"
    volumes:
      - /volume1/docker/qiandao/data:/usr/src/app/volume