version: "3"
services: 
  wiz:
    image: "wiznote/wizserver"
    container_name: "wiz"
    volumes: 
      - ./data/storage:/wiz/storage
      - ./data/localtime:/etc/localtime
    ports: 
      - "80:80"
    environment: 
      - "SEARCH=true"

volumes: 
  wizdata: