version: '2'
services:
  nexus3:
    container_name: nexus3
    image: sonatype/nexus3
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Duser.timezone=Asia/Shanghai
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - ./data/nexus:/nexus-data
