version: "2.2"
services: 
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    ports:
      - "7780:80"
      - "7706:3306"
    environment:
      USER: "root"
      PASSWD: "password"
      BIND_ADDRESS: "false"
    extra_hosts:
      - "smtp.exmail.qq.com:163.177.90.125"
    volumes:
      - ./data:/opt/zbox/
    restart: always