version: '3'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./data/data:/mosquitto/data
      - ./data/logs:/mosquitto/logs
      - ./data/conf:/mosquitto/config
    restart: unless-stopped

volumes:
  data:
  logs:
  conf: