version: '3'
bitwarden:
    container_name: bitwarden
    image: bitwarden/all
    environment:
      - UID=123
      - GID=123
    ports:
      - 443:443
    volumes:
      - /var/bitwarden:/var/bitwarden